apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  ports:
    - name: java
      protocol: TCP
      port: 25565
      targetPort: 25565
  selector:
    app: minecraft-server
  type: LoadBalancer
  loadBalancerIP: 192.168.2.242
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-be
  labels:
    app: minecraft-server
spec:
  ports:
    - name: be
      protocol: UDP
      port: 19132
      targetPort: 19132
  selector:
    app: minecraft-server
  type: LoadBalancer
  loadBalancerIP: 192.168.2.243

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-mc-claim
  labels:
    app: minecraft-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-mc-plugin-claim
  labels:
    app: minecraft-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-deployment
  labels:
    app: minecraft-server
spec:
  selector:
    matchLabels:
      app: minecraft-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
      - image: itzg/minecraft-server:latest
        imagePullPolicy: Always
        name: minecraft-server
        env:
        - name: EULA
          value: "TRUE"
        - name: TZ
          value: Asia/Tokyo
        - name: TYPE
          value: PAPER
        # - name: OVERRIDE_SERVER_PROPERTIES
        #   value: "TRUE"
        - name: DIFFICULTY
          value: normal
        - name: SPAWN_PROTECTION
          value: "4"
        - name: OPS
          valueFrom:
            secretKeyRef:
              name: mc-user
              key: ops
        #- name: OVERRIDE_WHITELIST
        #  value: "true"
        #- name: SIMULATION_DISTANCE
        #  value: "4"
        #- name: VIEW_DISTANCE
        #  value: "15"
        - name: ONLINE_MODE
          value: "FALSE"
        - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
          value: "true" 
        - name: REMOVE_OLD_MODS
          value: "TRUE"
        - name: REMOVE_OLD_MODS_INCLUDE
          value: "*.jar"
        - name: REMOVE_OLD_MODS_DEPTH
          value: "1"  
        resources:
          limits:
            memory: 2Gi
            cpu: 1500m
          requests:
            memory: 2Gi
            cpu: 1500m
        ports:
        - name: java
          containerPort: 25565
        - name: be
          containerPort: 19132
        volumeMounts:
        - name: minecraft-server-storage
          mountPath: /data
        - name: minecraft-plugins-dir
          mountPath: /plugins
      volumes:
      - name: minecraft-server-storage
        persistentVolumeClaim:
          claimName: pv-mc-claim
      - name: minecraft-plugins-dir
        persistentVolumeClaim:
          claimName: pv-mc-plugin-claim
